spring:
  application:
    name: hotel-reservation
  config:
    additional-location: file:\keys\
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ea
    password: cs544
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect

mail:
  host: smtp.gmail.com
  port: 587
  username: taxzitwentyfour@gmail.com
  password: piqjkdrnctkzyvjq
  protocol: smtp
  tls: true
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com
  debug: true

server:
  port: 8090
  servlet:
    context-path: "/api/v1"

msgs:
  registrations:
    subject: "Hotel Reservation Confirmation"
    welcome: "Hello %s, we’re excited to have you. Wherever you’re going, requesting a ride is just a tap away, Thank you for registering with Taxi24."